# graphqlpolicy monitor role
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: graphql-policy-monitor
rules:
  - apiGroups: ["example.com"]
    resources: ["graphqlpolicies"]
    verbs: ["get", "list", "watch"]