apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: api
  namespace: api-istio
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api1-gateway
  namespace: api-istio
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api1
  namespace: api-istio
spec:
  hosts:
  - '*'
  gateways:
  - api1-gateway
  http:
  - name: "api1 route"
    match:
    - uri:
        prefix: /api1
    rewrite:
      uri: /
    route:
    - destination:
        host: api1
  - match:
    route:
    - destination:
        host: api1
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api2
  namespace: api-istio
spec:
  hosts:
    - '*'
  gateways:
    - api1-gateway
  http:
    - name: "api2 route"
      match:
        - uri:
            prefix: /api2
      rewrite:
        uri: /
      route:
        - destination:
            host: api2
    - match:
      route:
        - destination:
            host: api2