apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: authz-opa
resources:
  - istio-envoy-filter.yaml
  - role.yaml
  - opa-istio.yaml
  - gcs-egress.yaml
  - rego-configmap.yaml
