apiVersion: v1
kind: ServiceAccount
metadata:
  name: nonistio1
  namespace: nonistio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nonistio2
  namespace: nonistio
---
apiVersion: v1
kind: Service
metadata:
  name: nonistio1
  namespace: nonistio
  labels:
    app: nonistio1
    service: nonistio1
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9080
  selector:
    app: nonistio1
---
apiVersion: v1
kind: Service
metadata:
  name: nonistio2
  namespace: nonistio
  labels:
    app: nonistio2
    service: nonistio2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9080
  selector:
    app: nonistio2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nonistio1
  namespace: nonistio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonistio1
      version: v1
  template:
    metadata:
      labels:
        app: nonistio1
        version: v1
    spec:
      serviceAccountName: nonistio1
      containers:
        - image: client/osltest
          imagePullPolicy: IfNotPresent
          name: nonistio1
          ports:
            - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nonistio2
  namespace: nonistio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonistio2
      version: v1
  template:
    metadata:
      labels:
        app: nonistio2
        version: v1
    spec:
      serviceAccountName: nonistio2
      containers:
        - image: client/osltest
          imagePullPolicy: IfNotPresent
          name: nonistio2
          ports:
            - containerPort: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nonistio1-gateway
  namespace: nonistio
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - '*'
      #- api1.api-istio.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nonistio1
  namespace: nonistio
spec:
  hosts:
    - '*'
  gateways:
    - nonistio1-gateway
  http:
    - name: "client1 route"
      match:
        - uri:
            prefix: /nonistio1
      route:
        - destination:
            host: nonistio1
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nonistio2
  namespace: nonistio
spec:
  hosts:
    - '*'
  gateways:
    - nonistio1-gateway
  http:
    - name: "client2 route"
      match:
        - uri:
            prefix: /nonistio2
      route:
        - destination:
            host: nonistio2
