apiVersion: v1
kind: ServiceAccount
metadata:
  name: api1
  namespace: api-istio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api2
  namespace: api-istio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
  namespace: api-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      api: api1
      version: v1
  template:
    metadata:
      labels:
        app: api
        api: api1
        version: v1
    spec:
      serviceAccountName: api1
      containers:
        - image: daime/http-dump
          imagePullPolicy: IfNotPresent
          name: api1
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
  namespace: api-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      api: api2
      version: v1
  template:
    metadata:
      labels:
        app: api
        api: api2
        version: v1
    spec:
      serviceAccountName: api2
      containers:
        - image: daime/http-dump
          imagePullPolicy: IfNotPresent
          name: api2
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"