############################################################
# Example configuration to bootstrap OPA-Istio sidecars.
############################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-istio-config
data:
  config.yaml: |
    services:
      - name: gcs
        url: https://storage.googleapis.com/test-opa-policy-bundles
    bundles:
      istio/authz:
        service: gcs
        resource: bundle.tar.gz
        persist: false
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        path: istio/authz/allow
    decision_logs:
      console: true