apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin-cluster2-se
spec:
  hosts:
    - httpbin.istio-testing.global
  location: MESH_INTERNAL
  ports:
    - name: http
      number: 80
      protocol: http
  resolution: DNS
  addresses:
    - 240.0.0.2
  endpoints:
    - address: $(minikube --profile cluster2 ip)
      ports:
        http: $(kubectl --context cluster2 get svc -n istio-system istio-ingressgateway -o=jsonpath='{.spec.ports[?(@.port==443)].nodePort}')
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: istio-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: governmentpaas/curl-ssl
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent